# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='catimage',
    version='2020.5',
    description='Use to cat an image to the terminal',
    python_requires='==3.*,>=3.5.0',
    project_urls={
        "documentation":
            "https://github.com/FredHappyface/Python.CatImage/blob/master/README.md",
        "homepage":
            "https://github.com/FredHappyface/Python.CatImage",
        "repository":
            "https://github.com/FredHappyface/Python.CatImage"
    },
    author='FredHappyface',
    classifiers=[
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Operating System :: OS Independent'
    ],
    entry_points={"console_scripts": ["catimage = catimage.catimage:cli"]},
    packages=['CatImage'],
    package_dir={"": "."},
    package_data={"catimage": ["*.png"]},
    install_requires=[
        'cli2gui==2020.*,>=2020.7.0', 'metprint==2020.*,>=2020.4.0',
        'pillow==7.*,>=7.1.1'
    ],
)
